spring:
  application:
    name: SportAdministrationSystem-test

  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: false

jwt:
  # будь-який довгий ключ, лише для тестів
  secret: test-test-test-test-test-test-test-test-123456
  access-exp-min: 60
  refresh-exp-days: 7
  access-ttl-minutes: 60
  refresh-ttl-days: 7

telegram:
  enabled: false          
  bot:
    token: dummy
    username: dummy
    chat-id: 0
    defaultChatId: 0
